# Generated by Django 4.0 on 2022-01-12 12:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0002_delete_intensitycategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sprint_distance', models.FloatField(blank=True, null=True)),
                ('sprint_time', models.FloatField(blank=True, null=True)),
                ('num_sprints', models.IntegerField(default=1)),
                ('on_hill', models.BooleanField(blank=True, null=True)),
                ('associated_cardio_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardio.cardioworkout')),
            ],
        ),
        migrations.CreateModel(
            name='IntervalTraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('load_interval', models.FloatField(default=0)),
                ('rest_interval', models.FloatField(default=0)),
                ('num_iterations', models.IntegerField(default=1)),
                ('overall_distance', models.FloatField(default=0)),
                ('associated_cardio_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardio.cardioworkout')),
            ],
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.FloatField()),
                ('time', models.FloatField()),
                ('elevation_gained', models.FloatField()),
                ('associated_cardio_workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardio.cardioworkout')),
            ],
        ),
    ]
