# Generated by Django 4.0 on 2022-01-12 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0003_sprints_intervaltraining_distance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sprints',
            new_name='Sprint',
        ),
    ]
