# Generated by Django 4.0 on 2022-01-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0004_rename_sprints_sprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='rest_measure',
            field=models.CharField(blank=True, default='seconds', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='rest_period',
            field=models.FloatField(default=0),
        ),
    ]
