# Generated by Django 4.0 on 2022-01-12 12:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_profile_height'),
        ('cardio', '0006_remove_cardioworkout_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardioworkout',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile'),
        ),
        migrations.AddField(
            model_name='cardioworkout',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
