# Generated by Django 4.0 on 2022-01-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardio', '0008_intervaltraining_load_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardioworkout',
            name='cardio_type',
            field=models.CharField(choices=[('interval training', 'interval training'), ('sprint', 'sprint'), ('distance run', 'distance run')], default='distance run', max_length=200),
        ),
    ]
