# Generated by Django 4.0 on 2022-01-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='meal',
            field=models.CharField(default='Snack', max_length=100),
        ),
    ]
