# Generated by Django 3.2.9 on 2022-01-01 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exerciseset',
            old_name='exercise_name',
            new_name='associated_exercise',
        ),
    ]
