# Generated by Django 4.0 on 2022-01-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_workout_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='repetitions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='sets',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='weight_lifted',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ExerciseSet',
        ),
    ]
