# Generated by Django 3.2.9 on 2022-01-01 04:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('priority', models.CharField(default='primary', max_length=100)),
                ('category', models.CharField(default='N/A', max_length=200)),
                ('description', models.CharField(default='Get Better', max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.profile')),
            ],
        ),
    ]
