# Generated by Django 4.0 on 2022-01-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20220101_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
