# Generated by Django 4.0 on 2022-01-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
