# Generated by Django 4.0 on 2022-01-01 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_weight_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
